### ISSUE TITLE
Champion list username fields reversed

### ISSUE THREAD

**Issue by LisaJo48** [OfficeDev/microsoft-teams-apps-champion-management#116]
Testing the interface and found this issue. my last name was automatically entered into the FirstName field and my first name in the LastName field.
![image](https://user-images.githubusercontent.com/46016140/185490923-54de8260-dce9-41c1-9234-525e5fca4ddc.png)

I've tried reinstalling to be sure I hadn't done something to cause it in my testing and it is still the case.

**Comment by LisaJo48** [comment]
When? This is a pretty front-and-center/first impression problem for us. We’re to deploy this by December. I need to be able to tell Leadership WHEN it will be fixed---not just that it will. Thanks.

A couple other questions I have not been able to get a clear answer to by researching myself, via MVPs, or by consulting with MS Partners:

  1.  I am having trouble changing the logo. Who/How can I ask for help on that?
  2.  And I am struggling to change the UI for the New Member fields from “Region” to “Company”. The Customization section states that this is possible with some instructions but they seem incomplete (or assume some knowledge/understanding which I don’t have).

     *   Can you tell me, yes or no, if these kinds of changes can be made and, if it they can be done,
        *   Will making those changes causing errors for updates/new version upgrades and, if it does not cause errors to do so,
           *   Who can I ask for help with it?
Thank you,

Lisa
Lisa JH Stebbins MDiv
M365 Collaboration Systems Specialist |BICOE | ITSS | The Heritage Group
C: 317 874 4902 | ***@***.******@***.***>



From: v-saikirang ***@***.***>
Sent: Friday, August 19, 2022 4:01 AM
To: OfficeDev/microsoft-teams-apps-champion-management ***@***.***>
Cc: Stebbins, Lisa ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [OfficeDev/microsoft-teams-apps-champion-management] Champion list username fields reversed (Issue #116)

Hi @LisaJo48, Thanks for your interest in the app and reaching out to us. This is a known issue with the app. This happens if the display name in your organization is configured as "LastName FirstName" in the Azure Active Directory. And I assume


Hi @LisaJo48<https://urldefense.com/v3/__https:/github.com/LisaJo48__;!!KX1o3_mqyiM!oLgMOzNfAZsSUnkF8Wszyzy9NFkiT69Rm-0tyqbCB2_syCdT_vgKZVwVBz7j3YvgyuHxL6UpsMVLzwH4QSsMwA$>,

Thanks for your interest in the app and reaching out to us.

This is a known issue with the app. This happens if the display name in your organization is configured as "LastName FirstName" in the Azure Active Directory. And I assume this is the case with you as well. We have plans to change this behavior in upcoming releases. Please watch out for the updates in git hub.

Please let me know if you need more information. Else we would like to close this ticket for now.
Thanks.

**Comment by v-saikirang** [comment]
Hi @LisaJo48,

We are tentatively planning the next release in early November and we will plan to include the change for this scenario as well in that release. 
And I see that you also wanted to to make some customizations to the app. Please note that customization requires an understanding on SPFX, React and type script. But we will not be able to support the custom versions of the app and our future upgrades to the app in git hub will not pass over to your custom version and those code upgrades will have to made manually to your custom version. Please let us know if you need more information.

Thanks.

**Comment by LisaJo48** [comment]
That will be great timing. Thanks for giving me that information so that I can set that issue aside in anticipation of the fix.

**Comment by LisaJo48** [comment]
Hello @v-saikirang. I am checking in to see if this fix will be included in the November release. This fix is critical to our ability to go Live with this tool in December.

**Comment by v-saikirang** [comment]
Hi @LisaJo48,

This issue will be part of our next release. Please note that we don't have a fixed date yet for the release. But currently we are targeting either end of November or early December which is tentative.

The Leaderboard ideally should display both first name and last name but since you have the first name and last name reversed it should at least show in "Last Name First Name". If that's not the case please share a screenshot of Leaderboard and contents of the "Members List" in Share Point site.

And after that fix the new champions will be added properly but the data for old champions which are already in "Members List" will have to fixed either manually in the list or for those users only it will shows reversed names in Leaderboard. 

Thanks.

**Comment by LisaJo48** [comment]
![image](https://user-images.githubusercontent.com/46016140/197032750-2c4da102-2286-4ba6-a242-b5b391b532dd.png)
![image](https://user-images.githubusercontent.com/46016140/197033043-1ae3322a-e8f7-4351-9559-04e6fcbf5c2e.png)
![image](https://user-images.githubusercontent.com/46016140/197033124-62f1919c-942a-482e-884f-797ffd1b885c.png)
![image](https://user-images.githubusercontent.com/46016140/197033206-52f61e22-07f0-4262-835a-b59691419c02.png)

**Comment by v-saikirang** [comment]
Hi @LisaJo48,

Thanks for the screenshots.

So I see that the Leader Board and the side bar is showing in the format of "FirstName LastName". But since you have Display Name set as "LastName FirstName" in your AD the values are reversed in the SP list while saving it. We have fixed this issue now so that whenever a new champion is added the values are stored in the SP list in the correct order. But this will take effect only for new entries after the upgrade. Any old values already stored in list will need to be changed manually if any. So the next release should handle your scenario.
Please let me know if you need more information.
Thanks.

**Comment by LisaJo48** [comment]
If I manually reverse the info that is in the Members List first and last name fields now so that they make sense to the end user when we go Live (which, unfortunately, sounds like that will be _before_ the release of the fix for this), will those changes still be correct after the fix is released or will I have to reverse them back?

**Comment by v-saikirang** [comment]
Hi @LisaJo48,

If you manually reverse info in members List now you don't have to reverse them back after the upgrade.

Please let me know if you need more information here.

Thanks.

**Comment by LisaJo48** [comment]
Thank you. It's so helpful to know what 'maintenance' I'm going to need to do as we deploy this.
