### ISSUE TITLE
Cannot add plug in to an existing Team

### ISSUE THREAD

**Issue by Jeckman1220** [OfficeDev/microsoft-teams-apps-champion-management#121]
Hello,

I tried adding the Champion Management Platform to an existing Team so that I can make posts and create engagement in my Team and direct those users to the CMP tab within the Team.

I hit the "+" in my Team to add the CMP tab, when I click the CMP plugin I get an error and CMP does not load.  "Something went wrong"

Thank you.

**Comment by LisaJo48** [comment]
In the time it took me to submit my issue, I see that you @Jeckman1220 have the same one! I will close mine so that we can learn and fix together.

**Comment by v-saikirang** [comment]
Hi @Jeckman1220 and @LisaJo48,

Thanks for raising the issue here. 

Can you please confirm if you have any issues accessing the CMP as a personal app.

And can you also confirm if you are able to add any other custom app to your team.

Thanks.

**Comment by LisaJo48** [comment]
@v-saikirang,
If I understand your question, I can access it via the left-hand menu in TEAMS where it is not related to a particular TEAM. I tried installing the app via a new [test] user by clicking on **Add to a team** rather than just **Add** and, interestingly, it didn't list the TEAMS to which I wanted to add it in the list of options. (The user is a member of the TEAM to which I want to add the tab and has the ability to create tabs).

Let me know if I misunderstood your question.

**Comment by v-saikirang** [comment]
Hi @LisaJo48,

Thanks for the response.
Can you please share a screenshot of what you see when you access the app through left menu. And were you able to add any other custom app to the team. Can you also try creating a sample teams and try to add the app.

Thanks.

**Comment by LisaJo48** [comment]
@v-saikirang 
Added Planner as a tab in the General channel of the TEAM: no issue. Worked as expected. Then I tried the CMP app again. This time it worked as expected, too. Interesting, at the time of my previous comment (1 hour prior), it did _not_ work. I then tried to install and add it to a TEAM via the side menu **Add to a team** link for a new user, This, too, worked because it displayed the name of the TEAM to which I wanted to add it (which, an hour ago, it did not). 

The good news is that it seems to be working but I am curious: did you do something to correct?

**Comment by v-saikirang** [comment]
Hi @LisaJo48,

I did not make any change. It could either be cache issue or a temporary Teams glitch. It may not be directly related to the app itself. Please let me know if you need more information.

Hi @Jeckman1220 ,

Can you please try this from your end and let us know if you are still facing the issue.

Thanks,
Sai.
