### ISSUE TITLE
Role field in the Members list

### ISSUE THREAD

**Issue by LisaJo48** [OfficeDev/microsoft-teams-apps-champion-management#133]
Hello, we have different 'levels' of champions in our company and would like to use the Role field to distinguish between them. Is there a way to set the field up so that it will allow for other types in addition to only 'Manager' and 'Champion' (the current state)?  For example, is it possible to set up the field so that

- If ROLE _contains_ "Champion"
- If ROLE _starts with_ "Champion"

If it is, then we can add our own additional descriptive word/phrase. Right now, if we add info to this field, the champion is not included in the app's features and functions.

**Comment by v-saikirang** [comment]
Hi @LisaJo48,

Currently the App works based on 3 different roles:
1) Manager
2)Champion(Status: Approved)
3)Champion(Status: Pending) - Not added to app as champion yet until approved by Manager from the "Manage Approvals" section. This happens when an employee submits the request to "Become a champion" from side bar in LeaderBoard.
All the components in the app show different views depending on the current user's role from one of the above 3.

So any changes to this property will not consider the user as champion and will not have access to the Champion features in the app.
If you still have a Business scenario that requires changing this value then you will have to create a custom version of the app and make code changes.

Please let me know if you need more information.
Thanks.

**Comment by LisaJo48** [comment]
Yes. That's what I expected which is why I was wondering if it were possible to change the programming expectation to "contains" or "starts with" instead of "equals".  The approved or pending would still apply to each as always. (I guess I don't consider a pending champion a unique role as much as a status.

**Comment by v-saikirang** [comment]
Hi @LisaJo48,
This scenario would require major code changes and since this is a very specific scenario, we will not be able to include this in our app template. Please consider customizing the app making the code changes to suit your requirements.

Thanks for sharing your feedback on all the features. We would definitely consider use cases that might be more common and applicable in majority of the scenarios and are compatible with current design of the app. You can extend and customize the App template for rest of the scenarios.

Thanks.
