### ISSUE TITLE
Question around security

### ISSUE THREAD

**Issue by Katieob19** [OfficeDev/microsoft-teams-apps-champion-management#144]
Under the FAQ for Teams App Templates (https://adoption.microsoft.com/en-us/microsoft-teams/app-templates/) it says, "App templates conform to recommended best practices for security and infrastructure, and all community-submitted changes are reviewed to ensure continued conformity." Can someone pls tell me:

- what does this vetting process look like?
- Is the code scanned?
- Are the people who do the scans trained in secure coding practices?
- Are they scanned in accordance to the O/S application security standards?

**Comment by v-saikirang** [comment]
Hi @Katieob19,

Thanks for reaching out to us.

We follow certain standards and processes for the app templates. I would like to highlight a few here:

1) The code is scanned for security vulnerabilities through ADO component governance and GITHUB dependabot. All the "High" and "Severe" alerts are fixed for before each release.
2) The apps are upgraded regularly to use the latest stable versions of the frameworks/tools involved. Ex: SPFX. 
3) SPFX projects also leverage "ESlint" to scan for code vulnerabilities and basic coding best practices.
4) Regular code reviews are done for all the projects.

Since the templates are open source it may not conform to every organization standards and in such cases the templates can be customized to suit your needs. Please let us know if you need additional information.
Thanks.
