### ISSUE TITLE
Participants in Tournament are not in the Leaderboard

### ISSUE THREAD

**Issue by LisaJo48** [OfficeDev/microsoft-teams-apps-champion-management#157]
Participants in a tournament from December 2022 (it is completed) are not listed on the Tournament Leaderboard. 
A kick-off tournament we held in December had 11 participants each completing 3-4 actions
![image](https://user-images.githubusercontent.com/46016140/226073825-8229e3e6-5086-4320-a3a8-63fe615964ed.png)

None of them are listed/ranked in the Tournament Leaderboard. I tried editing the entries in the User Actions list for one participant to see if it would update the leaderboard with the name but it did not make any difference.

Why are the 14 participants not included in the Tournament Leaderboard. How can I get the added?

**Comment by v-saikirang** [comment]
Hi @LisaJo48,

Thanks for reaching out to us.

Can you please confirm the status of the tournament "DnD 10 CMP Unvealing". Is it completed or inprogress. And please note that Tournaments is a separate module within CMP and the tournaments data is not stored in  "User Actions" list. The Tournaments data is not listed in "CMP Leaderboard". Tournaments data can be found only in LeaderBoard under "Tournament of Teams" module. And if the tournament is already Completed the data would show up only in "Tournaments Report".  Please let me know if you need additional information.

Thanks.

**Comment by LisaJo48** [comment]
The "DnD CMP Unveiling" is inactive/completed.

Yes. I am aware that Events and Tournaments are completely separate and that, unfortunately, their "counts" (i.e. points) for the same person do not interact to give the user a single total of points for their participation in the whole CMP platform. :( 

The leaderboard I was referencing was that of the Tournaments, not Events. 
![image](https://user-images.githubusercontent.com/46016140/226355376-86510e0b-2ca3-4f6d-86cb-6fabc19f08d6.png)

The names from the DnD CMP Unveiling tournament particpants are not listed above; only the ones who have participation, so far, in the "TEAM-Up!..." tournament are listed. I can't show you the names for security reasons, so you'll have to trust me on that one!

The "User Actions" list is for Tournaments, not Events. (Note at the top of the User Actions list screenshot it says "Tournament Name" for the grouping. The term "tournament" is not associated to or used in Events. 

FYI: The Events actions list is called "Event Track Details"

**Comment by v-saikirang** [comment]
Hi @LisaJo48 ,

"The names from the DnD CMP Unveiling tournament particpants are not listed above". - Can you please confirm if you meant the names are not listed in the "Tournament Leaderboard"? 

Thanks.

**Comment by LisaJo48** [comment]
That is correct. See earlier screenshot of the Tournament leaderboard. I cannot show you the names, however, for security reasons.

**Comment by LisaJo48** [comment]
Follow up: I review the User Actions list vs. Tournament leaderboard list manually. There should be 24 names of which 14 are displayed. All 14 participated in the active tournament named "TEAM-Up!..." and the 10 who are not listed participated in the inactive "DnD CMP Unveiling" tournament. All 24 were awarded appropriate Points in the User Action list but the 10 users who are not listed think they did not get their points.

Also, it's not shown in my screenshots but, the User column of the Tournament Leaderboard is showing [lastname firstname] (i.e. Smith John, Jones Sally). This needs to be corrected so that it reads [firstname last name] (i.e. John Smith, Sally Jones).

**Comment by v-saikirang** [comment]
Hi @LisaJo48,

In the Tournaments Leaderboard it will show only the participants of  "TEAM-Up!.." and the data pertaining to that tournament alone for that users since that is the selected tournament in the dropdown list. Since "DnD CMP Unveiling" is already completed it will not show up in the LeaderBoard. The details of the completed tournament can only be found in the "Tournament Report" from UI.

Can you please let me know if the First Name and Last Name in the member List are in the correct order. And May I know the format of "Display Name" from Azure AD in your tenant. Is it "Last Name, First Name"? Please confirm.
Thanks.

**Comment by v-saikirang** [comment]
Hi @LisaJo48,

As of now a user can view his points and rank only for a particular Tournament. And the Report is from Tournaments stand point. There is no report where a user can see the their cumulative information for all the tournaments that they participated. We will add this to our Feature Request Queue and assess/prioritize for future releases.

We will look in to the Name issue and update you shortly.

Thanks.

**Comment by v-saikirang** [comment]
Hi @LisaJo48,

It is by design we considered to show the "Display Name" from Azure in TOT module. The idea was to show the names as per the ORG's setting. Even in CMP we used the Display Name earlier but had to change it due to a limitation there. If we go for this change now it may cause inconsistency with the existing data/installation. We would still consider this feedback and add it to our backlog and assess in future. 

Thanks for your interest in the app and your feedback. It helps us prioritize our future line up of features for the app and understand real time scenarios.

Thanks.

**Comment by LisaJo48** [comment]
Thank you for the info. Then, why is our Event Leaderboard showing [firstname lastname] if it, too, is using the Azure display name? You would think they'd be consistent. So, whatever you did to make the Events Leaderboard display [firstname lastname], please apply the same thing to the Tournament Leaderboard. Consistency is important to the overall professional look of an app as well as less confusion to endusers.

**Comment by v-saikirang** [comment]
Hi @LisaJo48,

Sure. We will add this to our queue and assess the feasibility, impact and try to implement in our future releases based on our analysis.
Thanks for your feedback.
