### ISSUE TITLE
Error adding to Teams (via SharePoint AC)

### ISSUE THREAD

**Issue by SammyRasha** [OfficeDev/microsoft-teams-apps-champion-management#180]
I get the error when uploading the app to the sharepoint catalogue as well as when try to select "add to Teams". API permissions are granted, I've tried deleting and reuploading the app and it still doesn't work. Account is an E licensed Global Admin Account.

<img width="872" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/10238857/4dc1b60b-7cfe-4362-b7d4-e398182e2a41">
<img width="886" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/10238857/3f51ceeb-8613-4ae5-b9ba-a354c872f3bc">

<img width="827" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/10238857/7e40c395-4a80-4d09-8f57-29816fe933e2">

**Comment by SammyRasha** [comment]
Additional comment - I am seeing some customers facing this issue also

**Comment by v-saikirang** [comment]
Hi @SammyRasha,

Thanks for brining this up. We are looking in to this. We will get back to you shortly.

Thanks.

**Comment by jscaion** [comment]
I have the same issue . Let us know when you will have a solution.

![2023-10-09_18h09_20](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/147425760/3a0df93b-321e-4981-909e-984fe026087b)

**Comment by v-saikirang** [comment]
Hi @jscaion ,

Can you please confirm if you are trying for a fresh install of CMP app for the first time.

Thanks.

**Comment by SammyRasha** [comment]
Fresh install yes, cannot see in under manage apps in TAC

**Comment by v-saikirang** [comment]
Hi @SammyRasha,

We have noticed this issue too. There seems to be a glitch here. We are working on it. We will let you know shortly. Thanks for your patience.

Thanks.

**Comment by v-saikirang** [comment]
Hi @SammyRasha, @jscaion,

There seems to be a glitch with "Add to Teams". We are working on a hot fix but meanwhile if you wish you can try the below quick fix.

Quick fix: Instead of "Add to Teams" you can directly upload the attached zip file under "Manage Apps" in Teams Admin center. This zip is a Teams app package file with a slight change in the app version format in manifest file which was causing conflicts.  After the zip file is uploaded you can skip the "Add to Teams" step and rest of the steps are the same as in deployment guide.
![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/87538202/58cfe447-ab6f-4e34-a4ba-858a19806873)

Please me know if you see any issues.

[TeamsSPFxApp.zip](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/files/12856450/TeamsSPFxApp.zip)

**Comment by v-saikirang** [comment]
Hi @SammyRasha, Thanks for confirming. 

Hi @jscaion, Iam closing this ticket. If you still face any issues please open new ticket.
